### ISSUE TITLE
[FEATURE REQUEST] Shissu Notebook: option to switch the filter directions

### ISSUE THREAD

**Issue by mychaelo** [ESOUIMods/ShissuGuildTools#4]
Currently Shissu Notebook lets you filter by the following options:
Offline time longer than X
Membership longer than X
Gold donations bigger than X
Demote Players Yes/No

I would like to be able to switch the > filters into < counterparts, and mass-promote players instead of mass-demoting.

![notebook_demo](https://user-images.githubusercontent.com/2910415/91127865-cf4fcc00-e6af-11ea-8135-905481923a03.gif)

@Sharlikran

**Comment by Sharlikran** [comment]
I apologize. Since there is little to go on for a license except a few small lines of code that make it seem like there is a license I have no way to get permission to develop this. The current maintainer dis grant me permission but the original author has not.

This is to share with the current maintainer while I wait for permission from the author.

Lastly, I do not want to develop this software beyond some simple changes like the kiosk times. There are a few tying like about the tool so I ahbe made minor adjustments to it functions better.

If it helps you then you are welcome to use this version. I will probably not update anything about it though. I am sorry. I'm too busy with other things to really dissect this code.
